spring:
  datasource:
    url : jdbc:mysql://localhost:3306/test2?serverTimezone=GMT%2B8
    type : com.alibaba.druid.pool.DruidDataSource
    username : root
    password : 120316111
    driver-class-name : com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
